# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-30 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jedi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='questions',
        ),
        migrations.AddField(
            model_name='candidate',
            name='answer1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answer_one', to='jedi.Test'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='answer2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answer_two', to='jedi.Test'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='answer3',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answer_three', to='jedi.Test'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='question1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='question_one', to='jedi.Test'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='question2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='question_two', to='jedi.Test'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='question3',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='question_three', to='jedi.Test'),
        ),
        migrations.AddField(
            model_name='test',
            name='answer1',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'Nope')], default=1),
        ),
        migrations.AddField(
            model_name='test',
            name='answer2',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'Nope')], default=1),
        ),
        migrations.AddField(
            model_name='test',
            name='answer3',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'Nope')], default=1),
        ),
        migrations.AddField(
            model_name='test',
            name='question1',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='test',
            name='question2',
            field=models.CharField(default=2, max_length=50),
        ),
        migrations.AddField(
            model_name='test',
            name='question3',
            field=models.CharField(default=3, max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='jedi',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='planet',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='test',
            name='order_code',
            field=models.IntegerField(),
        ),
    ]
