# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-31 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jedi', '0002_auto_20190130_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='answer1',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='answer2',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='answer3',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='question1',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='question2',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='question3',
        ),
        migrations.AddField(
            model_name='test',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test', to='jedi.Candidate'),
        ),
    ]
